name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      # Set up virtual display for VS Code tests
      - name: Set up virtual display
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      # Run tests with xvfb-run
      - name: Test
        run: xvfb-run -a npm test

      - name: Build
        run: npm run compile